# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          curl -L -o /usr/local/bin/pivnet https://github.com/pivotal-cf/pivnet-cli/releases/download/v3.0.1/pivnet-linux-amd64-3.0.1  && \
              chmod 755 /usr/local/bin/pivnet
              pivnet login --api-token=$(apitoken)
    - task: Docker@2
      inputs:
        containerRegistry: 'Tanzu Registry'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'Harbor Registry'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'Harbor Registry'
        repository: 'harbor.buildmodernapps.com/tap/learningcenter'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
