#@ load("@ytt:data", "data")
---
apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: tap-install-workshop
spec:
  title: VMware Tanzu Application Platform Installation Demo
  description: An introduction to the installation of VMware Tanzu Application Platform
  vendor: tanzu.vmware.com
  difficulty: beginner
  duration: 180m
  url: https://github.com/tanzu-end-to-end/tap-install-workshop
  content:
    image: #@ "{}/tap-workshop/tap-install-workshop:latest".format(data.values.container_registry.hostname)
    files: #@ "github.com/{}/tap-install-workshop?ref={}".format(data.values.workshop_git.username,data.values.workshop_git.branch)
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: false
      editor:
        enabled: true
      slides:
        enabled: true
      docker:
        enabled: true
        storage: 1Gi
    env: 
    - name: TAP_PRODUCT_DOCS_BASE_URL
      value: #@ data.values.tap_product_docs_base_url
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: $(session_namespace)-cluster-resources-reader
      rules:
      - apiGroups: [apiextensions.k8s.io]
        resources: ["customresourcedefinitions"]
        verbs: ["get", "watch", "list"]
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: $(session_namespace)-cluster-resources
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: $(session_namespace)-cluster-resources-reader
      subjects:
      - kind: Group
        name: system:serviceaccounts:$(workshop_namespace)
        apiGroup: rbac.authorization.k8s.io